import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./common/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project XER",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="w-[calc(100%-100px)] mx-auto">

        {children}
        </div>
      </body>
    </html>
  );
}
